name: main

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: surdaft/snips.sh-notification-bot:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"   